#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json

[default_session]
startup_command = "tmuxinator start --append && exit || clear"
preview_command = "eza --all -1 --git --icons --color=always {}"

[[session]]
name = "xidots"
path = "~/.xidots"
preview_command = "git -C ~/.xidots status"

[[session]]
name = "Papers"
path = "~/Pictures/Wallpapers"
preview_command = "eza -1 --icons --color=always ~/Pictures/Wallpapers"

[[session]]
name = "Downloads"
path = "~/Downloads"

[[session]]
name = "Tmux config"
path = "~/.config/tmux"
startup_command = "nvim tmux.conf"
preview_command = "bat --color=always ~/.config/tmux/tmux.conf"
