# Enter resize mode with ALT + R and resize windows with H J K L
bind = SUPER ALT SHIFT, R, submap, resize
submap = resize
binde = , H, resizeactive, -50 0
binde = , J, resizeactive, 0 50
binde = , K, resizeactive, 0 -50
binde = , L, resizeactive, 50 0
bind = , C, centerwindow, 1
bind = , catchall, submap, reset
submap = reset


# Enter move mode with ALT + M and move windows with H J K L
bind = SUPER ALT SHIFT, M, submap, move
submap = move
binde = , H, moveactive, -50 0
binde = , K, moveactive, 0 -50
binde = , J, moveactive, 0 50
binde = , L, moveactive, 50 0
bind = , catchall, submap, reset
submap = reset
