# ----------------- Window Rules ------------------- #

# Calculator
windowrule = match:class org.gnome.Calculator, float 1

# Bitwarden
windowrule = match:class Bitwarden, float 1

# Opacities
windowrule = match:fullscreen 0, opacity 0.98 override
windowrule = match:class kitty|imv|swappy, opaque 1 # They use native transparency or we want them opaque
windowrule = match:xwayland 0, match:float 1, center 1  # Center all floating windows (not xwayland cause popups)

# Float, resize and center
# nmtui
windowrule {
  name = kitty-nmtui
  match:class = kitty-nmtui
  float = on
  size = (monitor_w*0.4) (monitor_h*0.6)
  center = 1
} 
# btop
windowrule {
  name = kitty-btop
  match:class = kitty-btop
  float = on
  size = (monitor_w*0.6) (monitor_h*0.7)
  center = 1
} 
# pulsemixer
windowrule {
  name = kitty-pulsemixer
  match:class = kitty-pulsemixer
  float = on
  size = (monitor_w*0.5) (monitor_h*0.6)
  center = 1
} 
# nwg-look
windowrule {
  name = nwg-look
  match:class = nwg-look
  float = on
  size = (monitor_w*0.5) (monitor_h*0.6)
  center = 1
} 
# blueman-manager
windowrule {
  name = blueman-manager
  match:class = blueman-manager
  float = on
  size = (monitor_w*0.5) (monitor_h*0.6)
  center = 1
} 
# pavucontrol
windowrule {
  name = pavucontrol
  match:class = org.pulseaudio.pavucontrol
  float = on
  size = (monitor_w*0.5) (monitor_h*0.6)
  center = 1
} 

# ------------------- Workspace rules ------------------- #
workspace = special:telegram, persistent true
workspace = special:obsidian, persistent true


# ------------------- Layer rules ------------------- #
layerrule = match:namespace selection, no_anim 1


# ----------------- Useful Windowrules --------------- #
windowrule = match:class .*, suppress_event maximize
windowrule = match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0, no_focus 1
windowrule = match:fullscreen 1, idle_inhibit always
