$configDir = /home/xitonight/.config/hypr
$sourcesDir = $configDir/source

source = $sourcesDir/nvidia.conf
source = $sourcesDir/env.conf
source = $sourcesDir/autostart.conf
source = $sourcesDir/misc.conf
source = $sourcesDir/appearence.conf
source = $sourcesDir/animations.conf
source = $sourcesDir/submaps.conf
source = $sourcesDir/input.conf
source = $sourcesDir/windowrules.conf

#monitor = HDMI-A-1, 1920x1080@75, 0x0, auto
monitor = , preferred, auto, 1
