[config]
reload_apps = true

[config.reload_apps_list]
kitty = true
gtk_theme = true

[config.wallpaper]
command = "swww"
arguments = [
  "img",
  "-t",
  "outer",
  "--transition-duration",
  "1.5",
  "--transition-step",
  "255",
  "--transition-fps",
  "60",
  "-f",
  "Nearest",
]
set = true

[templates.hyprland]
input_path = "~/.config/Ax-Shell/config/matugen/templates/hyprland-colors.conf"
output_path = "~/.config/Ax-Shell/config/hypr/colors.conf"

[templates.kitty]
input_path = "~/.config/matugen/templates/colors-kitty.conf"
output_path = "~/.config/kitty/colors.conf"
post_hook = "killall -SIGUSR1 kitty &"

[templates.rofi]
input_path = "~/.config/matugen/templates/colors-rofi.rasi"
output_path = "~/.cache/wal/colors-rofi.rasi"

[templates.slurp]
input_path = "~/.config/matugen/templates/colors-slurp.sh"
output_path = "~/.config/kitty/slurp.sh"

[templates.gtk3]
input_path = "~/.config/matugen/templates/colors.css"
output_path = "~/.config/gtk-3.0/colors.css"

[templates.gtk4]
input_path = "~/.config/matugen/templates/colors.css"
output_path = "~/.config/gtk-4.0/colors.css"

[templates.qt5ct]
input_path = "~/.config/matugen/templates/colors-qt.conf"
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = "~/.config/matugen/templates/colors-qt.conf"
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.nvim]
input_path = "~/.config/nvim/pywal/matugen.lua"
output_path = "~/.cache/wal/base46-dark.lua"

[templates.pywal]
input_path = "~/.config/matugen/templates/colors-pywal"
output_path = "~/.cache/wal/colors"

[templates.pywaljson]
input_path = "~/.config/matugen/templates/colors-pywal.json"
output_path = "~/.cache/wal/colors.json"
post_hook = "pywalfox update &"

[templates.fzf]
input_path = "~/.config/matugen/templates/colors-fzf"
output_path = "~/.zsh/fzf_theme"

[templates.pywalsh]
input_path = "~/.config/matugen/templates/colors.sh"
output_path = "~/.cache/wal/colors.sh"
post_hook = "walogram -B > /dev/null 2>&1 &"

[templates.pywalwalfile]
input_path = "~/.config/matugen/templates/wal"
output_path = "~/.cache/wal/wal"

[templates.ax-shell]
input_path = "~/.config/Ax-Shell/config/matugen/templates/ax-shell.css"
output_path = "~/.config/Ax-Shell/styles/colors.css"
post_hook = "fabric-cli exec ax-shell 'app.set_css()' &"

[config.custom_colors.red]
color = "#FF0000"
blend = true

[config.custom_colors.green]
color = "#00FF00"
blend = true

[config.custom_colors.yellow]
color = "#FFFF00"
blend = true

[config.custom_colors.blue]
color = "#0000FF"
blend = true

[config.custom_colors.magenta]
color = "#FF00FF"
blend = true

[config.custom_colors.cyan]
color = "#00FFFF"
blend = true

[config.custom_colors.white]
color = "#FFFFFF"
blend = true
